[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+multivalue,+mutable-globals,+reference-types,+bulk-memory,+simd128"]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
debug-assertions = false
overflow-checks = false
